<?php

namespace WB\AnalyticsBundle\Repository;

/**
 * WBUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WBUserRepository extends \Doctrine\ORM\EntityRepository
{
}
