<?php

namespace WB\WizbiinauteBundle\Repository;

/**
 * WizbiinauteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WizbiinauteRepository extends \Doctrine\ORM\EntityRepository
{
}
